CaroGFaimBundle\Entity\plat:
    type: entity
    table: null
    repositoryClass: CaroGFaimBundle\Repository\platRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
            unique: true
        note:
            type: integer
        annotations:
            type: string
            length: 255
    lifecycleCallbacks: {  }
